version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: users-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: users_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: users-backend
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      DB_USER: appuser
      DB_PASS: 1234
      DB_NAME: users_db
      # JWT Configuration (256-bit secret)
      JWT_SECRET: Jt5Te5WjUV13hI3IFra04Al8S4YiniGTMPi7+Ai9fUE=
      # SMTP Configuration (optional - for email verification)
      # Uncomment and configure these to enable email sending
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: "587"
      SMTP_USER: matiasvidal2404@gmail.com
      SMTP_PASS: "efac tqpy kryf vxfb"
      SMTP_FROM: matiasvidal2404@gmail.com
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
